
server:  
  port: 8101

spring:
  application:
    name: cloud-greeter-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    com.inmensia: 'DEBUG'
