
server:
  port: ${CLOUD_GREETER_API_PORT}

spring:
  application:
    name: cloud-greeter-api

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
    com.inmensia: DEBUG

cloud:
  greeter:
    api:
      greeterServiceUrl: http://cloud-greeter-service/api/v1/greeting
