
server:
  port: ${CLOUD_GREETER_SERVICE_PORT}

spring:
  application:
    name: cloud-greeter-service

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
  
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
    com.inmensia: DEBUG
